const DIVISIONS = ["Kids", "Premiers Pas", "Espoir", "Semi-Pro", "Elite"];
const GENDERS   = ["Men", "Women"];

const DIVISION_META = {
  Kids:           { desc: "6–12 ans · Mouvements adaptés" },
  "Premiers Pas": { desc: "Débutant · Poids du corps" },
  Espoir:         { desc: "Intermédiaire · Légère charge" },
  "Semi-Pro":     { desc: "Avancé · Charge modérée" },
  Elite:          { desc: "Compétition · Charge lourde" },
};

const DIVISION_THEME = {
  Kids:           { accent: "#fdcb6e", load: "#e17055", tag: "Kids" },
  "Premiers Pas": { accent: "#f4c35a", load: "#e53e3e", tag: "Starter" },
  Espoir:         { accent: "#82d9ff", load: "#e53e3e", tag: "Division 3" },
  "Semi-Pro":     { accent: "#c084fc", load: "#e53e3e", tag: "Division 2" },
  Elite:          { accent: "#d4a843", load: "#e53e3e", tag: "Division 1", timecap: "#d4a843", border: "rgba(212,168,67,0.35)" },
};

// Kids exercises: {text, cat} objects for coloured badges.
// All other divisions: plain strings.
const CIRCUIT_LIBRARY = [

  // ═══════════════════════════════════════════════════════════════
  //  KIDS
  // ═══════════════════════════════════════════════════════════════

  {
    id: "kids-m-1", division: "Kids", gender: "Men",
    round: "Circuit 1", title: "Fun Circuit", subtitle: "Découvre le calisthenics",
    timeCap: "5 min",
    exercises: [
      { text: "10 Tractions australiennes", cat: "PULL" },
      { text: "15 Push-up sur genoux",      cat: "PUSH" },
      { text: "20 Air squat",               cat: "LEGS" },
      { text: "15 Dips sur banc",           cat: "PUSH" },
      { text: "30 Jumping jack",            cat: "CARDIO" },
    ],
  },
  {
    id: "kids-m-2", division: "Kids", gender: "Men",
    round: "Circuit 2", title: "Force Junior", subtitle: "Corps en action",
    timeCap: "4 min",
    exercises: [
      { text: "8 Tractions australiennes",  cat: "PULL" },
      { text: "15 Squat sauté",             cat: "LEGS" },
      { text: "10 Push-up",                 cat: "PUSH" },
      { text: "20s Gainage haut",           cat: "CORE" },
      { text: "12 Dips sur banc",           cat: "PUSH" },
    ],
  },
  {
    id: "kids-m-3", division: "Kids", gender: "Men",
    round: "Circuit 3", title: "Ninja Mode", subtitle: "Challenge junior",
    timeCap: "5 min",
    exercises: [
      { text: "12 Tractions australiennes", cat: "PULL" },
      { text: "15 Fente alternée",          cat: "LEGS" },
      { text: "12 Push-up",                 cat: "PUSH" },
      { text: "15 Squat sauté",              cat: "LEGS" },
      { text: "10 Dips sur banc",           cat: "PUSH" },
      { text: "20s Superman",               cat: "CORE" },
    ],
  },
  {
    id: "kids-m-4", division: "Kids", gender: "Men",
    round: "Circuit 4", title: "Jungle Run", subtitle: "Cardio & force",
    timeCap: "4 min",
    exercises: [
      { text: "8 Tractions australiennes",  cat: "PULL" },
      { text: "12 Air squat",               cat: "LEGS" },
      { text: "8 Push-up",                  cat: "PUSH" },
      { text: "20 Jumping jack",            cat: "CARDIO" },
      { text: "10 Dips sur banc",           cat: "PUSH" },
    ],
  },
  {
    id: "kids-m-5", division: "Kids", gender: "Men",
    round: "Circuit 5", title: "Super Junior", subtitle: "Le défi ultime",
    timeCap: "6 min",
    exercises: [
      { text: "15 Tractions australiennes", cat: "PULL" },
      { text: "25 Air squat",               cat: "LEGS" },
      { text: "20 Push-up sur genoux",      cat: "PUSH" },
      { text: "30s Gainage haut",           cat: "CORE" },
      { text: "20 Dips sur banc",           cat: "PUSH" },
      { text: "10 Tractions australiennes",  cat: "PULL" },
    ],
  },
  {
    id: "kids-m-s", division: "Kids", gender: "Men",
    round: "Statiques", title: "Force Statique", subtitle: "Tiens la position !",
    timeCap: "8 min",
    exercises: [
      { text: "3× 10s Deadhang (barre)",      cat: "PULL" },
      { text: "3× 20s Wall sit",              cat: "LEGS" },
      { text: "3× 10s Support hold (banc)",   cat: "PUSH" },
      { text: "3× 15s Gainage haut",          cat: "CORE" },
      { text: "3× 10s Superman allongé",      cat: "CORE" },
    ],
  },

  {
    id: "kids-w-1", division: "Kids", gender: "Women",
    round: "Circuit 1", title: "Fun Circuit", subtitle: "Découvre le calisthenics",
    timeCap: "5 min",
    exercises: [
      { text: "8 Tractions australiennes",  cat: "PULL" },
      { text: "12 Push-up sur genoux",      cat: "PUSH" },
      { text: "18 Air squat",               cat: "LEGS" },
      { text: "12 Dips sur banc",           cat: "PUSH" },
      { text: "30 Jumping jack",            cat: "CARDIO" },
    ],
  },
  {
    id: "kids-w-2", division: "Kids", gender: "Women",
    round: "Circuit 2", title: "Force Junior", subtitle: "Corps en action",
    timeCap: "4 min",
    exercises: [
      { text: "6 Tractions australiennes",  cat: "PULL" },
      { text: "12 Squat sauté",             cat: "LEGS" },
      { text: "10 Push-up sur genoux",      cat: "PUSH" },
      { text: "20s Gainage haut",           cat: "CORE" },
      { text: "10 Dips sur banc",           cat: "PUSH" },
    ],
  },
  {
    id: "kids-w-3", division: "Kids", gender: "Women",
    round: "Circuit 3", title: "Ninja Mode", subtitle: "Challenge junior",
    timeCap: "5 min",
    exercises: [
      { text: "10 Tractions australiennes", cat: "PULL" },
      { text: "14 Fente alternée",          cat: "LEGS" },
      { text: "10 Push-up sur genoux",      cat: "PUSH" },
      { text: "12 Squat sauté",              cat: "LEGS" },
      { text: "8 Dips sur banc",            cat: "PUSH" },
      { text: "20s Superman",               cat: "CORE" },
    ],
  },
  {
    id: "kids-w-4", division: "Kids", gender: "Women",
    round: "Circuit 4", title: "Jungle Run", subtitle: "Cardio & force",
    timeCap: "4 min",
    exercises: [
      { text: "6 Tractions australiennes",  cat: "PULL" },
      { text: "12 Air squat",               cat: "LEGS" },
      { text: "8 Push-up sur genoux",       cat: "PUSH" },
      { text: "20 Jumping jack",            cat: "CARDIO" },
      { text: "8 Dips sur banc",            cat: "PUSH" },
    ],
  },
  {
    id: "kids-w-5", division: "Kids", gender: "Women",
    round: "Circuit 5", title: "Super Junior", subtitle: "Le défi ultime",
    timeCap: "6 min",
    exercises: [
      { text: "12 Tractions australiennes", cat: "PULL" },
      { text: "20 Air squat",               cat: "LEGS" },
      { text: "16 Push-up sur genoux",      cat: "PUSH" },
      { text: "30s Gainage haut",           cat: "CORE" },
      { text: "16 Dips sur banc",           cat: "PUSH" },
      { text: "8 Tractions australiennes",   cat: "PULL" },
    ],
  },
  {
    id: "kids-w-s", division: "Kids", gender: "Women",
    round: "Statiques", title: "Force Statique", subtitle: "Tiens la position !",
    timeCap: "8 min",
    exercises: [
      { text: "3× 8s Deadhang (barre)",      cat: "PULL" },
      { text: "3× 20s Wall sit",             cat: "LEGS" },
      { text: "3× 8s Support hold (banc)",   cat: "PUSH" },
      { text: "3× 15s Gainage haut",         cat: "CORE" },
      { text: "3× 10s Superman allongé",     cat: "CORE" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  //  PREMIERS PAS
  //  Ordre: PULL → LEGS → PUSH → PULL → LEGS → PUSH
  // ═══════════════════════════════════════════════════════════════

  {
    id: "pp-m-1", division: "Premiers Pas", gender: "Men",
    round: "Routine 1", title: "CBL Premiers Pas", subtitle: "Accessible et lisible",
    timeCap: "6 min",
    exercises: [
      "5 Pull-up",
      "15 Goblet squat @15 kg",
      "20 Push-up",
      "10 Pull-up",
      "15 Air squat",
      "15 Dips",
      "5 Chest Pull-up ou 1 Muscle-up",
      "10 Dips @10 kg",
    ],
  },
  {
    id: "pp-m-2", division: "Premiers Pas", gender: "Men",
    round: "Routine 2", title: "CBL Premiers Pas", subtitle: "Force de base",
    timeCap: "7 min",
    exercises: [
      "4 Chest Pull-up",
      "10 Goblet squat @20 kg",
      "15 Push-up",
      "8 Pull-up",
      "20 Air squat",
      "12 Dips",
      "8 Dips @5 kg",
      "12 Push-up",
    ],
  },
  {
    id: "pp-m-3", division: "Premiers Pas", gender: "Men",
    round: "Routine 3", title: "CBL Premiers Pas", subtitle: "Endurance corps",
    timeCap: "6 min",
    exercises: [
      "6 Pull-up",
      "20 Air squat",
      "20 Push-up",
      "8 Pull-up",
      "15 Goblet squat @12 kg",
      "12 Dips @5 kg",
    ],
  },
  {
    id: "pp-m-4", division: "Premiers Pas", gender: "Men",
    round: "Routine 4", title: "CBL Premiers Pas", subtitle: "Technique & volume",
    timeCap: "7 min",
    exercises: [
      "5 Chest Pull-up",
      "15 Goblet squat @12 kg",
      "18 Push-up",
      "5 Pull-up",
      "20 Air squat",
      "10 Push-up",
      "8 Dips",
      "12 Dips @5 kg",
    ],
  },
  {
    id: "pp-m-5", division: "Premiers Pas", gender: "Men",
    round: "Routine 5", title: "CBL Premiers Pas", subtitle: "Montée en puissance",
    timeCap: "6 min",
    exercises: [
      "8 Pull-up",
      "12 Goblet squat @15 kg",
      "20 Push-up",
      "6 Chest Pull-up",
      "20 Dips",
      "10 Pull-up",
    ],
  },
  {
    id: "pp-m-s", division: "Premiers Pas", gender: "Men",
    round: "Statiques", title: "Isométrique PP", subtitle: "Renforcement statique",
    timeCap: "8 min",
    exercises: [
      "3× 12s Deadhang actif (scapulas)",
      "3× 20s Wall sit",
      "3× 10s Support hold barres",
      "3× 20s Gainage haut",
      "2× 10s L-sit genoux (sol)",
      "2× 10s Bottom dip hold",
    ],
  },

  {
    id: "pp-w-1", division: "Premiers Pas", gender: "Women",
    round: "Routine 1", title: "CBL Premiers Pas", subtitle: "Accessible et lisible",
    timeCap: "6 min",
    exercises: [
      "4 Pull-up",
      "12 Goblet squat @12 kg",
      "16 Push-up",
      "8 Pull-up",
      "14 Air squat",
      "12 Dips",
      "4 Chest Pull-up ou 1 Muscle-up",
      "8 Dips @5 kg",
    ],
  },
  {
    id: "pp-w-2", division: "Premiers Pas", gender: "Women",
    round: "Routine 2", title: "CBL Premiers Pas", subtitle: "Force de base",
    timeCap: "7 min",
    exercises: [
      "3 Chest Pull-up",
      "8 Goblet squat @15 kg",
      "12 Push-up",
      "6 Pull-up",
      "18 Air squat",
      "10 Dips",
      "6 Dips @5 kg",
      "10 Push-up",
    ],
  },
  {
    id: "pp-w-3", division: "Premiers Pas", gender: "Women",
    round: "Routine 3", title: "CBL Premiers Pas", subtitle: "Endurance corps",
    timeCap: "6 min",
    exercises: [
      "5 Pull-up",
      "16 Air squat",
      "16 Push-up",
      "6 Pull-up",
      "12 Goblet squat @10 kg",
      "10 Dips @5 kg",
    ],
  },
  {
    id: "pp-w-4", division: "Premiers Pas", gender: "Women",
    round: "Routine 4", title: "CBL Premiers Pas", subtitle: "Technique & volume",
    timeCap: "7 min",
    exercises: [
      "4 Chest Pull-up",
      "12 Goblet squat @10 kg",
      "14 Push-up",
      "4 Pull-up",
      "18 Air squat",
      "8 Push-up",
      "6 Dips",
      "10 Dips @5 kg",
    ],
  },
  {
    id: "pp-w-5", division: "Premiers Pas", gender: "Women",
    round: "Routine 5", title: "CBL Premiers Pas", subtitle: "Montée en puissance",
    timeCap: "6 min",
    exercises: [
      "6 Pull-up",
      "10 Goblet squat @12 kg",
      "16 Push-up",
      "4 Chest Pull-up",
      "16 Dips",
      "8 Pull-up",
    ],
  },
  {
    id: "pp-w-s", division: "Premiers Pas", gender: "Women",
    round: "Statiques", title: "Isométrique PP", subtitle: "Renforcement statique",
    timeCap: "8 min",
    exercises: [
      "3× 10s Deadhang actif (scapulas)",
      "3× 20s Wall sit",
      "3× 8s Support hold barres",
      "3× 20s Gainage haut",
      "2× 8s L-sit genoux (sol)",
      "2× 8s Bottom dip hold",
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  //  ESPOIR
  //  Ordre: COMPOUND → LEGS → PULL → PUSH → COMPOUND → LEGS → PUSH
  // ═══════════════════════════════════════════════════════════════

  {
    id: "espoir-m-1", division: "Espoir", gender: "Men",
    round: "Routine 1", title: "CBL Espoir", subtitle: "Open qualifier",
    timeCap: "8 min",
    exercises: [
      "1 Muscle-up + 10 Dips + 5 Pull-up",
      "15 Goblet squat @40 kg",
      "10 Pull-up @5 kg",
      "30 Dips",
      "15 Goblet squat @40 kg",
      "20 Dips @10 kg",
      "1 Muscle-up ou 4 Chest Pull-up",
      "10 Dips @20 kg",
    ],
  },
  {
    id: "espoir-m-2", division: "Espoir", gender: "Men",
    round: "Routine 2", title: "CBL Espoir", subtitle: "Endurance technique",
    timeCap: "9 min",
    exercises: [
      "2 Muscle-up",
      "12 Goblet squat @40 kg",
      "12 Pull-up @5 kg",
      "25 Dips",
      "12 Goblet squat @35 kg",
      "18 Dips @10 kg",
      "5 Muscle-up ou 10 Chest Pull-up",
      "10 Pull-up",
    ],
  },
  {
    id: "espoir-m-3", division: "Espoir", gender: "Men",
    round: "Routine 3", title: "CBL Espoir", subtitle: "Force progressive",
    timeCap: "8 min",
    exercises: [
      "3 Chest Pull-up",
      "12 Goblet squat @40 kg",
      "30 Push-up",
      "10 Pull-up @5 kg",
      "20 Dips @5 kg",
      "1 Muscle-up ou 4 Chest Pull-up",
      "15 Pull-up",
      "20 Dips",
    ],
  },
  {
    id: "espoir-m-4", division: "Espoir", gender: "Men",
    round: "Routine 4", title: "CBL Espoir", subtitle: "Volume & résistance",
    timeCap: "9 min",
    exercises: [
      "1 Muscle-up + 5 Chest Pull-up",
      "15 Goblet squat @35 kg",
      "15 Pull-up @5 kg",
      "20 Dips @10 kg",
      "15 Goblet squat @24 kg",
      "30 Push-up",
      "10 Dips @20 kg",
    ],
  },
  {
    id: "espoir-m-5", division: "Espoir", gender: "Men",
    round: "Routine 5", title: "CBL Espoir", subtitle: "Circuit complet",
    timeCap: "8 min",
    exercises: [
      "3 Muscle-up",
      "15 Goblet squat @40 kg",
      "12 Pull-up @5 kg",
      "25 Dips @5 kg",
      "15 Goblet squat @35 kg",
      "10 Chest Pull-up",
      "20 Dips",
    ],
  },
  {
    id: "espoir-m-s", division: "Espoir", gender: "Men",
    round: "Statiques", title: "Isométrique Espoir", subtitle: "Force de maintien",
    timeCap: "10 min",
    exercises: [
      "3× 12s Deadhang @5 kg",
      "3× 20s Bottom squat @30 kg",
      "3× 10s L-sit barres basses",
      "3× 12s Support hold @10 kg",
      "2× 10s Deadhang pesé @8 kg",
      "2× 10s Top pull-up hold @5 kg",
    ],
  },

  {
    id: "espoir-w-1", division: "Espoir", gender: "Women",
    round: "Routine 1", title: "CBL Espoir", subtitle: "Open qualifier",
    timeCap: "8 min",
    exercises: [
      "1 Muscle-up ou 4 Chest Pull-up",
      "12 Goblet squat @30 kg",
      "8 Pull-up @5 kg",
      "24 Dips",
      "12 Goblet squat @20 kg",
      "16 Dips @10 kg",
      "12 Pull-up",
      "8 Dips @15 kg",
    ],
  },
  {
    id: "espoir-w-2", division: "Espoir", gender: "Women",
    round: "Routine 2", title: "CBL Espoir", subtitle: "Endurance technique",
    timeCap: "9 min",
    exercises: [
      "3 Chest Pull-up",
      "10 Goblet squat @30 kg",
      "10 Pull-up @5 kg",
      "20 Dips",
      "10 Goblet squat @25 kg",
      "14 Dips @10 kg",
      "4 Chest Pull-up",
      "8 Pull-up",
    ],
  },
  {
    id: "espoir-w-3", division: "Espoir", gender: "Women",
    round: "Routine 3", title: "CBL Espoir", subtitle: "Force progressive",
    timeCap: "8 min",
    exercises: [
      "2 Chest Pull-up",
      "10 Goblet squat @28 kg",
      "24 Push-up",
      "8 Pull-up @5 kg",
      "16 Dips @5 kg",
      "1 Muscle-up ou 3 Chest Pull-up",
      "14 Dips",
    ],
  },
  {
    id: "espoir-w-4", division: "Espoir", gender: "Women",
    round: "Routine 4", title: "CBL Espoir", subtitle: "Volume & résistance",
    timeCap: "9 min",
    exercises: [
      "1 Muscle-up ou 3 Chest Pull-up",
      "12 Goblet squat @30 kg",
      "12 Pull-up @5 kg",
      "16 Dips @10 kg",
      "12 Goblet squat @20 kg",
      "24 Push-up",
      "8 Dips @15 kg",
    ],
  },
  {
    id: "espoir-w-5", division: "Espoir", gender: "Women",
    round: "Routine 5", title: "CBL Espoir", subtitle: "Circuit complet",
    timeCap: "8 min",
    exercises: [
      "2 Muscle-up ou 6 Chest Pull-up",
      "12 Goblet squat @30 kg",
      "10 Pull-up @5 kg",
      "20 Dips @5 kg",
      "10 Goblet squat @25 kg",
      "8 Chest Pull-up",
      "16 Dips",
    ],
  },
  {
    id: "espoir-w-s", division: "Espoir", gender: "Women",
    round: "Statiques", title: "Isométrique Espoir", subtitle: "Force de maintien",
    timeCap: "10 min",
    exercises: [
      "3× 10s Deadhang @5 kg",
      "3× 20s Bottom squat @25 kg",
      "3× 8s L-sit barres basses",
      "3× 10s Support hold @BW",
      "2× 8s Deadhang pesé @5 kg",
      "2× 8s Top pull-up hold @5 kg",
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  //  SEMI-PRO
  //  Ordre: COMPOUND lourd → LEGS → PULL → PUSH → COMPOUND → LEGS → PUSH
  // ═══════════════════════════════════════════════════════════════

  {
    id: "sp-m-1", division: "Semi-Pro", gender: "Men",
    round: "Routine 1", title: "CBL Semi-Pro", subtitle: "Challenge technique",
    timeCap: "10 min",
    exercises: [
      "3 Muscle-up @5 kg",
      "15 Goblet squat @50 kg",
      "12 Pull-up @10 kg",
      "40 Dips",
      "15 Goblet squat @45 kg",
      "5 Muscle-up",
      "15 Dips @30 kg",
      "8 Muscle-up ou 15 Chest Pull-up",
    ],
  },
  {
    id: "sp-m-2", division: "Semi-Pro", gender: "Men",
    round: "Routine 2", title: "CBL Semi-Pro", subtitle: "Force & volume",
    timeCap: "11 min",
    exercises: [
      "1 Muscle-up @10 kg",
      "18 Goblet squat @50 kg",
      "10 Pull-up @10 kg",
      "40 Push-up",
      "5 Muscle-up",
      "20 Dips @20 kg",
      "12 Pull-up @10 kg",
      "10 Dips @40 kg",
    ],
  },
  {
    id: "sp-m-3", division: "Semi-Pro", gender: "Men",
    round: "Routine 3", title: "CBL Semi-Pro", subtitle: "Endurance avancée",
    timeCap: "10 min",
    exercises: [
      "2 Muscle-up @5 kg",
      "15 Goblet squat @48 kg",
      "15 Pull-up @10 kg",
      "35 Dips",
      "8 Muscle-up",
      "40 Push-up",
      "10 Dips @35 kg",
    ],
  },
  {
    id: "sp-m-4", division: "Semi-Pro", gender: "Men",
    round: "Routine 4", title: "CBL Semi-Pro", subtitle: "Montée en charge",
    timeCap: "11 min",
    exercises: [
      "5 Chest Pull-up @10 kg",
      "18 Goblet squat @50 kg",
      "12 Pull-up @10 kg",
      "45 Dips",
      "3 Muscle-up @5 kg",
      "15 Pull-up",
      "12 Dips @40 kg",
      "6 Muscle-up",
    ],
  },
  {
    id: "sp-m-5", division: "Semi-Pro", gender: "Men",
    round: "Routine 5", title: "CBL Semi-Pro", subtitle: "Circuit pro",
    timeCap: "10 min",
    exercises: [
      "1 Muscle-up @10 kg",
      "18 Goblet squat @50 kg",
      "15 Pull-up @10 kg",
      "40 Dips",
      "3 Muscle-up @5 kg",
      "40 Push-up",
      "5 Muscle-up",
      "10 Dips @40 kg",
    ],
  },
  {
    id: "sp-m-s", division: "Semi-Pro", gender: "Men",
    round: "Statiques", title: "Isométrique Semi-Pro", subtitle: "Maîtrise du corps",
    timeCap: "10 min",
    exercises: [
      "3× 10s Deadhang pesé @15 kg",
      "3× 15s Bottom squat @40 kg",
      "3× 10s L-sit barres",
      "3× 12s Support hold @20 kg",
      "2× 8s Top pull-up hold pesé @15 kg",
      "2× 8s Support hold pesé @20 kg",
    ],
  },

  {
    id: "sp-w-1", division: "Semi-Pro", gender: "Women",
    round: "Routine 1", title: "CBL Semi-Pro", subtitle: "Challenge technique",
    timeCap: "10 min",
    exercises: [
      "2 Muscle-up @5 kg",
      "12 Goblet squat @38 kg",
      "10 Pull-up @5 kg",
      "30 Dips",
      "12 Goblet squat @35 kg",
      "4 Muscle-up",
      "12 Dips @20 kg",
      "6 Muscle-up ou 10 Chest Pull-up",
    ],
  },
  {
    id: "sp-w-2", division: "Semi-Pro", gender: "Women",
    round: "Routine 2", title: "CBL Semi-Pro", subtitle: "Force & volume",
    timeCap: "11 min",
    exercises: [
      "1 Muscle-up @5 kg",
      "14 Goblet squat @36 kg",
      "8 Pull-up @5 kg",
      "30 Push-up",
      "4 Muscle-up",
      "16 Dips @15 kg",
      "10 Pull-up @5 kg",
      "8 Dips @25 kg",
    ],
  },
  {
    id: "sp-w-3", division: "Semi-Pro", gender: "Women",
    round: "Routine 3", title: "CBL Semi-Pro", subtitle: "Endurance avancée",
    timeCap: "10 min",
    exercises: [
      "1 Muscle-up @5 kg",
      "12 Goblet squat @36 kg",
      "10 Pull-up @5 kg",
      "28 Dips",
      "5 Muscle-up",
      "30 Push-up",
      "8 Dips @25 kg",
    ],
  },
  {
    id: "sp-w-4", division: "Semi-Pro", gender: "Women",
    round: "Routine 4", title: "CBL Semi-Pro", subtitle: "Montée en charge",
    timeCap: "11 min",
    exercises: [
      "4 Chest Pull-up @5 kg",
      "14 Goblet squat @38 kg",
      "10 Pull-up @5 kg",
      "32 Dips",
      "2 Muscle-up @5 kg",
      "12 Pull-up",
      "8 Dips @25 kg",
      "4 Muscle-up",
    ],
  },
  {
    id: "sp-w-5", division: "Semi-Pro", gender: "Women",
    round: "Routine 5", title: "CBL Semi-Pro", subtitle: "Circuit pro",
    timeCap: "10 min",
    exercises: [
      "1 Muscle-up @5 kg",
      "14 Goblet squat @38 kg",
      "10 Pull-up @5 kg",
      "30 Dips",
      "2 Muscle-up",
      "30 Push-up",
      "4 Muscle-up",
      "8 Dips @25 kg",
    ],
  },
  {
    id: "sp-w-s", division: "Semi-Pro", gender: "Women",
    round: "Statiques", title: "Isométrique Semi-Pro", subtitle: "Maîtrise du corps",
    timeCap: "10 min",
    exercises: [
      "3× 8s Deadhang pesé @10 kg",
      "3× 15s Bottom squat @32 kg",
      "3× 8s L-sit barres",
      "3× 10s Support hold @15 kg",
      "2× 6s Top pull-up hold pesé @10 kg",
      "2× 6s Support hold pesé @15 kg",
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  //  ELITE
  //  Ordre: COMPOUND lourd → LEGS → PULL pesé → PUSH → COMPOUND → LEGS → PUSH lourd
  //  Aucun muscle-up consécutif — toujours séparé par jambes ou tirage
  // ═══════════════════════════════════════════════════════════════

  {
    id: "elite-m-1", division: "Elite", gender: "Men",
    round: "Routine 1", title: "CBL Elite", subtitle: "Battle endurance",
    timeCap: "12 min",
    exercises: [
      "1 Muscle-up @15 kg",
      "20 Goblet squat @60 kg",
      "3 Muscle-up @10 kg",
      "20 Pull-up @15 kg",
      "50 Dips",
      "5 Muscle-up @10 kg",
      "50 Push-up",
      "7 Muscle-up",
      "10 Dips @50 kg",
    ],
  },
  {
    id: "elite-m-2", division: "Elite", gender: "Men",
    round: "Routine 2", title: "CBL Elite", subtitle: "Force maximale",
    timeCap: "12 min",
    exercises: [
      "1 Muscle-up @15 kg",
      "18 Goblet squat @65 kg",
      "3 Muscle-up @15 kg",
      "20 Pull-up @15 kg",
      "5 Muscle-up @10 kg",
      "50 Push-up",
      "8 Muscle-up",
      "10 Dips @50 kg",
    ],
  },
  {
    id: "elite-m-3", division: "Elite", gender: "Men",
    round: "Routine 3", title: "CBL Elite", subtitle: "Endurance explosive",
    timeCap: "11 min",
    exercises: [
      "3 Muscle-up @15 kg",
      "20 Goblet squat @60 kg",
      "15 Pull-up @15 kg",
      "50 Dips",
      "5 Muscle-up @10 kg",
      "50 Push-up",
      "12 Chest Pull-up",
      "7 Muscle-up",
      "10 Dips @50 kg",
    ],
  },
  {
    id: "elite-m-4", division: "Elite", gender: "Men",
    round: "Routine 4", title: "CBL Elite", subtitle: "Circuit lourd",
    timeCap: "12 min",
    exercises: [
      "1 Muscle-up @15 kg",
      "20 Goblet squat @60 kg",
      "5 Muscle-up @10 kg",
      "15 Pull-up @20 kg",
      "50 Dips",
      "50 Push-up",
      "5 Muscle-up",
      "10 Dips @55 kg",
    ],
  },
  {
    id: "elite-m-5", division: "Elite", gender: "Men",
    round: "Routine 5", title: "CBL Elite", subtitle: "Finale compétition",
    timeCap: "12 min",
    exercises: [
      "1 Muscle-up @15 kg",
      "18 Goblet squat @65 kg",
      "3 Muscle-up @15 kg",
      "20 Pull-up @15 kg",
      "50 Dips",
      "5 Muscle-up @10 kg",
      "50 Push-up",
      "8 Muscle-up",
      "10 Dips @55 kg",
      "12 Chest Pull-up",
    ],
  },
  {
    id: "elite-m-s", division: "Elite", gender: "Men",
    round: "Statiques", title: "Isométrique Elite", subtitle: "Contrôle absolu",
    timeCap: "12 min",
    exercises: [
      "3× 8s Deadhang pesé @25 kg",
      "3× 15s Bottom squat @50 kg",
      "3× 10s L-sit full barres",
      "2× 8s Top pull-up hold pesé @20 kg",
      "3× 10s Support hold @30 kg",
      "2× 6s Support hold pesé @30 kg",
      "2× 5s Bottom dip hold pesé @20 kg",
    ],
  },

  {
    id: "elite-w-1", division: "Elite", gender: "Women",
    round: "Routine 1", title: "CBL Elite", subtitle: "Battle endurance",
    timeCap: "12 min",
    exercises: [
      "1 Muscle-up @5 kg",
      "18 Goblet squat @40 kg",
      "3 Muscle-up",
      "12 Pull-up @5 kg",
      "40 Dips",
      "4 Muscle-up",
      "40 Push-up",
      "12 Chest Pull-up",
      "8 Dips @20 kg",
    ],
  },
  {
    id: "elite-w-2", division: "Elite", gender: "Women",
    round: "Routine 2", title: "CBL Elite", subtitle: "Force maximale",
    timeCap: "12 min",
    exercises: [
      "1 Muscle-up @8 kg",
      "16 Goblet squat @42 kg",
      "3 Muscle-up @5 kg",
      "15 Pull-up @5 kg",
      "4 Muscle-up",
      "40 Push-up",
      "5 Muscle-up",
      "8 Dips @22 kg",
    ],
  },
  {
    id: "elite-w-3", division: "Elite", gender: "Women",
    round: "Routine 3", title: "CBL Elite", subtitle: "Endurance explosive",
    timeCap: "11 min",
    exercises: [
      "2 Muscle-up @5 kg",
      "18 Goblet squat @40 kg",
      "12 Pull-up @5 kg",
      "40 Dips",
      "4 Muscle-up",
      "40 Push-up",
      "5 Muscle-up",
      "10 Chest Pull-up",
      "8 Dips @20 kg",
    ],
  },
  {
    id: "elite-w-4", division: "Elite", gender: "Women",
    round: "Routine 4", title: "CBL Elite", subtitle: "Circuit lourd",
    timeCap: "12 min",
    exercises: [
      "1 Muscle-up @8 kg",
      "16 Goblet squat @42 kg",
      "4 Muscle-up @5 kg",
      "12 Pull-up @8 kg",
      "40 Dips",
      "40 Push-up",
      "5 Muscle-up",
      "8 Dips @25 kg",
    ],
  },
  {
    id: "elite-w-5", division: "Elite", gender: "Women",
    round: "Routine 5", title: "CBL Elite", subtitle: "Finale compétition",
    timeCap: "12 min",
    exercises: [
      "1 Muscle-up @8 kg",
      "16 Goblet squat @42 kg",
      "3 Muscle-up @5 kg",
      "15 Pull-up @5 kg",
      "40 Dips",
      "4 Muscle-up",
      "40 Push-up",
      "5 Muscle-up",
      "8 Dips @25 kg",
      "10 Chest Pull-up",
    ],
  },
  {
    id: "elite-w-s", division: "Elite", gender: "Women",
    round: "Statiques", title: "Isométrique Elite", subtitle: "Contrôle absolu",
    timeCap: "12 min",
    exercises: [
      "3× 6s Deadhang pesé @15 kg",
      "3× 15s Bottom squat @35 kg",
      "3× 8s L-sit full barres",
      "2× 6s Top pull-up hold pesé @12 kg",
      "3× 8s Support hold @20 kg",
      "2× 5s Support hold pesé @20 kg",
      "2× 5s Bottom dip hold pesé @15 kg",
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  //  BOSS CARDS — 1 par division × 2 genres
  //  Mouvements autorisés : pompes, tractions, dips, squat,
  //  goblet squat, muscle-up. Sets & Reps format street workout.
  // ═══════════════════════════════════════════════════════════════

  // ── Kids Boss — COMPLET · PDC uniquement ────────────────────────
  // 4 PULL · 3 PUSH · 3 LEGS  →  découverte équilibrée 3 chaînes
  {
    id: "kids-m-boss", division: "Kids", gender: "Men", isBoss: true,
    round: "BOSS · Grand Défi Junior",
    title: "Le Grand Défi",
    subtitle: "Prouve que tu es prêt pour le niveau suivant",
    timeCap: "15 min · 3 rounds",
    exercises: [
      { text: "10 Tractions australiennes",          cat: "PULL" },
      { text: "15 Squat sauté",                      cat: "LEGS" },
      { text: "12 Pompes",                           cat: "PUSH" },
      { text: "8 Tractions australiennes",           cat: "PULL", unbroken: true },
      { text: "10 Dips sur banc",                    cat: "PUSH" },
      { text: "15 Squat",                            cat: "LEGS" },
      { text: "6 Tractions australiennes",           cat: "PULL", unbroken: true },
      { text: "12 Pompes explosives",                cat: "PUSH" },
      { text: "20 Squat",                            cat: "LEGS" },
      { text: "8 Tractions australiennes",           cat: "PULL" },
    ],
  },
  {
    id: "kids-w-boss", division: "Kids", gender: "Women", isBoss: true,
    round: "BOSS · Grand Défi Junior",
    title: "Le Grand Défi",
    subtitle: "Prouve que tu es prête pour le niveau suivant",
    timeCap: "15 min · 3 rounds",
    exercises: [
      { text: "8 Tractions australiennes",           cat: "PULL" },
      { text: "15 Squat sauté",                      cat: "LEGS" },
      { text: "10 Pompes",                           cat: "PUSH" },
      { text: "6 Tractions australiennes",           cat: "PULL", unbroken: true },
      { text: "8 Dips sur banc",                     cat: "PUSH" },
      { text: "15 Squat",                            cat: "LEGS" },
      { text: "5 Tractions australiennes",           cat: "PULL", unbroken: true },
      { text: "10 Pompes",                           cat: "PUSH" },
      { text: "20 Squat",                            cat: "LEGS" },
      { text: "6 Tractions australiennes",           cat: "PULL" },
    ],
  },

  // ── Premiers Pas Boss — SPÉ-PULL · 60% tirage · sans MU ────────
  // 6 PULL · 2 PUSH · 2 LEGS  →  max T +10 kg / D +20 kg
  {
    id: "pp-m-boss", division: "Premiers Pas", gender: "Men", isBoss: true,
    round: "BOSS · Test de Passage",
    title: "Test de Passage",
    subtitle: "Le ticket d'entrée pour Espoir",
    timeCap: "18 min · 3 rounds",
    exercises: [
      "15 Tractions",
      "20 Squat",
      "12 Tractions",
      "15 Pompes",
      { text: "10 Tractions",                        unbroken: true },
      "20 Dips",
      "8 Tractions @8 kg",
      { text: "6 Tractions @10 kg",                  unbroken: true },
      "20 Goblet squat @20 kg",
      "15 Dips @20 kg",
    ],
  },
  {
    id: "pp-w-boss", division: "Premiers Pas", gender: "Women", isBoss: true,
    round: "BOSS · Test de Passage",
    title: "Test de Passage",
    subtitle: "Le ticket d'entrée pour Espoir",
    timeCap: "18 min · 3 rounds",
    exercises: [
      "10 Tractions",
      "20 Squat",
      "8 Tractions",
      "12 Pompes",
      { text: "6 Tractions",                         unbroken: true },
      "12 Dips",
      "6 Tractions @5 kg",
      { text: "5 Tractions @8 kg",                   unbroken: true },
      "20 Goblet squat @12 kg",
      "12 Dips @10 kg",
    ],
  },

  // ── Espoir Boss — COMPLET · MU frais en ouverture + clôture ────
  // 4 PULL · 4 PUSH · 2 LEGS  →  max MU PDC / T +20 kg / D +30 kg
  {
    id: "espoir-m-boss", division: "Espoir", gender: "Men", isBoss: true,
    round: "BOSS · Brevet Intermédiaire",
    title: "Brevet Intermédiaire",
    subtitle: "Franchis la porte du Semi-Pro",
    timeCap: "20 min · 4 rounds",
    exercises: [
      "3 Muscle-up",
      "20 Squat @40 kg",
      "15 Pompes",
      "12 Tractions @15 kg",
      "15 Goblet squat @24 kg",
      "12 Dips @20 kg",
      { text: "10 Tractions @20 kg",                 unbroken: true },
      "20 Pompes",
      "12 Dips @25 kg",
      { text: "2 Muscle-up",                         unbroken: true },
    ],
  },
  {
    id: "espoir-w-boss", division: "Espoir", gender: "Women", isBoss: true,
    round: "BOSS · Brevet Intermédiaire",
    title: "Brevet Intermédiaire",
    subtitle: "Franchis la porte du Semi-Pro",
    timeCap: "20 min · 4 rounds",
    exercises: [
      "2 Muscle-up",
      "20 Squat @30 kg",
      "12 Pompes",
      "10 Tractions @10 kg",
      "15 Goblet squat @16 kg",
      "10 Dips @15 kg",
      { text: "8 Tractions @15 kg",                  unbroken: true },
      "15 Pompes",
      "10 Dips @20 kg",
      { text: "2 Muscle-up",                         unbroken: true },
    ],
  },

  // ── Semi-Pro Boss — SPÉ-PUSH · 60% push · iso ──────────────────
  // 6 PUSH · 2 PULL · 2 LEGS  →  max MU +10 / D +50 / T +30 kg
  {
    id: "sp-m-boss", division: "Semi-Pro", gender: "Men", isBoss: true,
    round: "BOSS · Challenge Compétiteur",
    title: "Challenge Compétiteur",
    subtitle: "Le seuil de l'Elite",
    timeCap: "22 min · 5 rounds",
    exercises: [
      "6 Muscle-up",
      "25 Pompes",
      "20 Dips @30 kg",
      "20 Goblet squat @50 kg",
      { text: "15 Dips @40 kg + 10s iso position basse", unbroken: true },
      "15 Tractions @25 kg",
      "25 Pompes",
      "20 Dips @35 kg",
      "25 Goblet squat @40 kg",
      { text: "20 Pompes",                            unbroken: true },
    ],
  },
  {
    id: "sp-w-boss", division: "Semi-Pro", gender: "Women", isBoss: true,
    round: "BOSS · Challenge Compétiteur",
    title: "Challenge Compétiteur",
    subtitle: "Le seuil de l'Elite",
    timeCap: "22 min · 5 rounds",
    exercises: [
      "4 Muscle-up",
      "20 Pompes",
      "15 Dips @20 kg",
      "20 Goblet squat @32 kg",
      { text: "12 Dips @30 kg + 10s iso position basse", unbroken: true },
      "10 Tractions @20 kg",
      "20 Pompes",
      "15 Dips @25 kg",
      "20 Goblet squat @28 kg",
      { text: "15 Pompes",                            unbroken: true },
    ],
  },

  // ── Elite Boss — COMPLET INTENSIF · MU @max en clôture ─────────
  // 4 PULL · 4 PUSH · 2 LEGS  →  max MU +15 / D +60 / T +40 / S +70 kg
  {
    id: "elite-m-boss", division: "Elite", gender: "Men", isBoss: true,
    round: "BOSS · Circuit Maître",
    title: "Circuit Maître",
    subtitle: "Le test ultime du streetworkout",
    timeCap: "30 min · 6 rounds",
    exercises: [
      "15 Tractions @30 kg",
      "20 Goblet squat @60 kg",
      "20 Dips @40 kg",
      "30 Pompes",
      { text: "10 Tractions @40 kg",                 unbroken: true },
      "20 Goblet squat @70 kg",
      "20 Dips @50 kg",
      "25 Pompes",
      { text: "15 Tractions @35 kg",                 unbroken: true },
      "10 Muscle-up @15 kg",
    ],
  },
  {
    id: "elite-w-boss", division: "Elite", gender: "Women", isBoss: true,
    round: "BOSS · Circuit Maître",
    title: "Circuit Maître",
    subtitle: "Le test ultime du streetworkout",
    timeCap: "30 min · 6 rounds",
    exercises: [
      "10 Tractions @20 kg",
      "20 Goblet squat @40 kg",
      "15 Dips @30 kg",
      "25 Pompes",
      { text: "8 Tractions @30 kg",                  unbroken: true },
      "20 Goblet squat @50 kg",
      "15 Dips @40 kg",
      "20 Pompes",
      { text: "10 Tractions @25 kg",                 unbroken: true },
      "6 Muscle-up @10 kg",
    ],
  },
];
