const DIVISIONS = ["Kids", "Premiers Pas", "Espoir", "Semi-Pro", "Elite"];
const GENDERS   = ["Men", "Women"];

const DIVISION_META = {
  Kids:           { desc: "6–12 ans · Mouvements adaptés" },
  "Premiers Pas": { desc: "Débutant · Poids du corps" },
  Espoir:         { desc: "Intermédiaire · Légère charge" },
  "Semi-Pro":     { desc: "Avancé · Charge modérée" },
  Elite:          { desc: "Compétition · Charge lourde" },
};

const DIVISION_THEME = {
  Kids:           { accent: "#fdcb6e", load: "#e17055", tag: "Kids" },
  "Premiers Pas": { accent: "#f4c35a", load: "#e53e3e", tag: "Starter" },
  Espoir:         { accent: "#82d9ff", load: "#e53e3e", tag: "Division 3" },
  "Semi-Pro":     { accent: "#c084fc", load: "#e53e3e", tag: "Division 2" },
  Elite:          { accent: "#d4a843", load: "#e53e3e", tag: "Division 1", timecap: "#d4a843", border: "rgba(212,168,67,0.35)" },
};

// Kids exercises: {text, cat} objects for coloured badges.
// All other divisions: plain strings.
const CIRCUIT_LIBRARY = [

  // ═══════════════════════════════════════════════════════════════
  //  KIDS
  // ═══════════════════════════════════════════════════════════════

  {
    id: "kids-m-1", division: "Kids", gender: "Men",
    round: "Circuit 1", title: "Fun Circuit", subtitle: "Découvre le calisthenics",
    timeCap: "5 min",
    exercises: [
      { text: "10 Tractions australiennes", cat: "PULL" },
      { text: "15 Push-up sur genoux",      cat: "PUSH" },
      { text: "20 Air squat",               cat: "LEGS" },
      { text: "15 Dips sur banc",           cat: "PUSH" },
      { text: "30 Jumping jack",            cat: "CARDIO" },
    ],
  },
  {
    id: "kids-m-2", division: "Kids", gender: "Men",
    round: "Circuit 2", title: "Force Junior", subtitle: "Corps en action",
    timeCap: "4 min",
    exercises: [
      { text: "8 Tractions australiennes",  cat: "PULL" },
      { text: "15 Squat sauté",             cat: "LEGS" },
      { text: "10 Push-up",                 cat: "PUSH" },
      { text: "20s Gainage haut",           cat: "CORE" },
      { text: "12 Dips sur banc",           cat: "PUSH" },
    ],
  },
  {
    id: "kids-m-3", division: "Kids", gender: "Men",
    round: "Circuit 3", title: "Ninja Mode", subtitle: "Challenge junior",
    timeCap: "5 min",
    exercises: [
      { text: "12 Tractions australiennes", cat: "PULL" },
      { text: "15 Fente alternée",          cat: "LEGS" },
      { text: "12 Push-up",                 cat: "PUSH" },
      { text: "10 Mountain climber",        cat: "CARDIO" },
      { text: "10 Dips sur banc",           cat: "PUSH" },
      { text: "20s Superman",               cat: "CORE" },
    ],
  },
  {
    id: "kids-m-4", division: "Kids", gender: "Men",
    round: "Circuit 4", title: "Jungle Run", subtitle: "Cardio & force",
    timeCap: "4 min",
    exercises: [
      { text: "8 Tractions australiennes",  cat: "PULL" },
      { text: "12 Air squat",               cat: "LEGS" },
      { text: "8 Push-up",                  cat: "PUSH" },
      { text: "20 Jumping jack",            cat: "CARDIO" },
      { text: "10 Dips sur banc",           cat: "PUSH" },
    ],
  },
  {
    id: "kids-m-5", division: "Kids", gender: "Men",
    round: "Circuit 5", title: "Super Junior", subtitle: "Le défi ultime",
    timeCap: "6 min",
    exercises: [
      { text: "15 Tractions australiennes", cat: "PULL" },
      { text: "25 Air squat",               cat: "LEGS" },
      { text: "20 Push-up sur genoux",      cat: "PUSH" },
      { text: "30s Gainage haut",           cat: "CORE" },
      { text: "20 Dips sur banc",           cat: "PUSH" },
      { text: "10 Burpee simplifié",        cat: "CARDIO" },
    ],
  },
  {
    id: "kids-m-s", division: "Kids", gender: "Men",
    round: "Statiques", title: "Force Statique", subtitle: "Tiens la position !",
    timeCap: "8 min",
    exercises: [
      { text: "3× 10s Deadhang (barre)",      cat: "PULL" },
      { text: "3× 20s Wall sit",              cat: "LEGS" },
      { text: "3× 10s Support hold (banc)",   cat: "PUSH" },
      { text: "3× 15s Gainage haut",          cat: "CORE" },
      { text: "3× 10s Superman allongé",      cat: "CORE" },
    ],
  },

  {
    id: "kids-w-1", division: "Kids", gender: "Women",
    round: "Circuit 1", title: "Fun Circuit", subtitle: "Découvre le calisthenics",
    timeCap: "5 min",
    exercises: [
      { text: "8 Tractions australiennes",  cat: "PULL" },
      { text: "12 Push-up sur genoux",      cat: "PUSH" },
      { text: "18 Air squat",               cat: "LEGS" },
      { text: "12 Dips sur banc",           cat: "PUSH" },
      { text: "30 Jumping jack",            cat: "CARDIO" },
    ],
  },
  {
    id: "kids-w-2", division: "Kids", gender: "Women",
    round: "Circuit 2", title: "Force Junior", subtitle: "Corps en action",
    timeCap: "4 min",
    exercises: [
      { text: "6 Tractions australiennes",  cat: "PULL" },
      { text: "12 Squat sauté",             cat: "LEGS" },
      { text: "10 Push-up sur genoux",      cat: "PUSH" },
      { text: "20s Gainage haut",           cat: "CORE" },
      { text: "10 Dips sur banc",           cat: "PUSH" },
    ],
  },
  {
    id: "kids-w-3", division: "Kids", gender: "Women",
    round: "Circuit 3", title: "Ninja Mode", subtitle: "Challenge junior",
    timeCap: "5 min",
    exercises: [
      { text: "10 Tractions australiennes", cat: "PULL" },
      { text: "14 Fente alternée",          cat: "LEGS" },
      { text: "10 Push-up sur genoux",      cat: "PUSH" },
      { text: "8 Mountain climber",         cat: "CARDIO" },
      { text: "8 Dips sur banc",            cat: "PUSH" },
      { text: "20s Superman",               cat: "CORE" },
    ],
  },
  {
    id: "kids-w-4", division: "Kids", gender: "Women",
    round: "Circuit 4", title: "Jungle Run", subtitle: "Cardio & force",
    timeCap: "4 min",
    exercises: [
      { text: "6 Tractions australiennes",  cat: "PULL" },
      { text: "12 Air squat",               cat: "LEGS" },
      { text: "8 Push-up sur genoux",       cat: "PUSH" },
      { text: "20 Jumping jack",            cat: "CARDIO" },
      { text: "8 Dips sur banc",            cat: "PUSH" },
    ],
  },
  {
    id: "kids-w-5", division: "Kids", gender: "Women",
    round: "Circuit 5", title: "Super Junior", subtitle: "Le défi ultime",
    timeCap: "6 min",
    exercises: [
      { text: "12 Tractions australiennes", cat: "PULL" },
      { text: "20 Air squat",               cat: "LEGS" },
      { text: "16 Push-up sur genoux",      cat: "PUSH" },
      { text: "30s Gainage haut",           cat: "CORE" },
      { text: "16 Dips sur banc",           cat: "PUSH" },
      { text: "8 Burpee simplifié",         cat: "CARDIO" },
    ],
  },
  {
    id: "kids-w-s", division: "Kids", gender: "Women",
    round: "Statiques", title: "Force Statique", subtitle: "Tiens la position !",
    timeCap: "8 min",
    exercises: [
      { text: "3× 8s Deadhang (barre)",      cat: "PULL" },
      { text: "3× 20s Wall sit",             cat: "LEGS" },
      { text: "3× 8s Support hold (banc)",   cat: "PUSH" },
      { text: "3× 15s Gainage haut",         cat: "CORE" },
      { text: "3× 10s Superman allongé",     cat: "CORE" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  //  PREMIERS PAS
  //  Ordre: PULL → LEGS → PUSH → PULL → LEGS → PUSH
  // ═══════════════════════════════════════════════════════════════

  {
    id: "pp-m-1", division: "Premiers Pas", gender: "Men",
    round: "Routine 1", title: "CBL Premiers Pas", subtitle: "Accessible et lisible",
    timeCap: "6 min",
    exercises: [
      "5 Pull-up",
      "15 Goblet Squat @15 kg",
      "20 Push-up",
      "10 Pull-up",
      "15 Air squat",
      "15 Dips",
      "5 Chest Pull-up ou 1 Muscle-up",
      "10 Dips @10 kg",
    ],
  },
  {
    id: "pp-m-2", division: "Premiers Pas", gender: "Men",
    round: "Routine 2", title: "CBL Premiers Pas", subtitle: "Force de base",
    timeCap: "7 min",
    exercises: [
      "4 Chest Pull-up",
      "10 Goblet Squat @20 kg",
      "15 Push-up",
      "8 Pull-up",
      "20 Air squat",
      "12 Dips",
      "8 Dips @5 kg",
      "12 Push-up",
    ],
  },
  {
    id: "pp-m-3", division: "Premiers Pas", gender: "Men",
    round: "Routine 3", title: "CBL Premiers Pas", subtitle: "Endurance corps",
    timeCap: "6 min",
    exercises: [
      "6 Pull-up",
      "20 Air squat",
      "20 Push-up",
      "8 Pull-up",
      "15 Goblet Squat @12 kg",
      "12 Dips @5 kg",
    ],
  },
  {
    id: "pp-m-4", division: "Premiers Pas", gender: "Men",
    round: "Routine 4", title: "CBL Premiers Pas", subtitle: "Technique & volume",
    timeCap: "7 min",
    exercises: [
      "5 Chest Pull-up",
      "15 Goblet Squat @12 kg",
      "18 Push-up",
      "5 Pull-up",
      "20 Air squat",
      "10 Push-up",
      "8 Dips",
      "12 Dips @5 kg",
    ],
  },
  {
    id: "pp-m-5", division: "Premiers Pas", gender: "Men",
    round: "Routine 5", title: "CBL Premiers Pas", subtitle: "Montée en puissance",
    timeCap: "6 min",
    exercises: [
      "8 Pull-up",
      "12 Goblet Squat @15 kg",
      "20 Push-up",
      "6 Chest Pull-up",
      "20 Dips",
      "10 Pull-up",
    ],
  },
  {
    id: "pp-m-s", division: "Premiers Pas", gender: "Men",
    round: "Statiques", title: "Isométrique PP", subtitle: "Renforcement statique",
    timeCap: "8 min",
    exercises: [
      "3× 12s Deadhang actif (scapulas)",
      "3× 20s Wall sit",
      "3× 10s Support hold barres",
      "3× 20s Gainage haut",
      "2× 10s L-sit genoux (sol)",
      "2× 10s Bottom dip hold",
    ],
  },

  {
    id: "pp-w-1", division: "Premiers Pas", gender: "Women",
    round: "Routine 1", title: "CBL Premiers Pas", subtitle: "Accessible et lisible",
    timeCap: "6 min",
    exercises: [
      "4 Pull-up",
      "12 Goblet Squat @12 kg",
      "16 Push-up",
      "8 Pull-up",
      "14 Air squat",
      "12 Dips",
      "4 Chest Pull-up ou 1 Muscle-up",
      "8 Dips @5 kg",
    ],
  },
  {
    id: "pp-w-2", division: "Premiers Pas", gender: "Women",
    round: "Routine 2", title: "CBL Premiers Pas", subtitle: "Force de base",
    timeCap: "7 min",
    exercises: [
      "3 Chest Pull-up",
      "8 Goblet Squat @15 kg",
      "12 Push-up",
      "6 Pull-up",
      "18 Air squat",
      "10 Dips",
      "6 Dips @5 kg",
      "10 Push-up",
    ],
  },
  {
    id: "pp-w-3", division: "Premiers Pas", gender: "Women",
    round: "Routine 3", title: "CBL Premiers Pas", subtitle: "Endurance corps",
    timeCap: "6 min",
    exercises: [
      "5 Pull-up",
      "16 Air squat",
      "16 Push-up",
      "6 Pull-up",
      "12 Goblet Squat @10 kg",
      "10 Dips @5 kg",
    ],
  },
  {
    id: "pp-w-4", division: "Premiers Pas", gender: "Women",
    round: "Routine 4", title: "CBL Premiers Pas", subtitle: "Technique & volume",
    timeCap: "7 min",
    exercises: [
      "4 Chest Pull-up",
      "12 Goblet Squat @10 kg",
      "14 Push-up",
      "4 Pull-up",
      "18 Air squat",
      "8 Push-up",
      "6 Dips",
      "10 Dips @5 kg",
    ],
  },
  {
    id: "pp-w-5", division: "Premiers Pas", gender: "Women",
    round: "Routine 5", title: "CBL Premiers Pas", subtitle: "Montée en puissance",
    timeCap: "6 min",
    exercises: [
      "6 Pull-up",
      "10 Goblet Squat @12 kg",
      "16 Push-up",
      "4 Chest Pull-up",
      "16 Dips",
      "8 Pull-up",
    ],
  },
  {
    id: "pp-w-s", division: "Premiers Pas", gender: "Women",
    round: "Statiques", title: "Isométrique PP", subtitle: "Renforcement statique",
    timeCap: "8 min",
    exercises: [
      "3× 10s Deadhang actif (scapulas)",
      "3× 20s Wall sit",
      "3× 8s Support hold barres",
      "3× 20s Gainage haut",
      "2× 8s L-sit genoux (sol)",
      "2× 8s Bottom dip hold",
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  //  ESPOIR
  //  Ordre: COMPOUND → LEGS → PULL → PUSH → COMPOUND → LEGS → PUSH
  // ═══════════════════════════════════════════════════════════════

  {
    id: "espoir-m-1", division: "Espoir", gender: "Men",
    round: "Routine 1", title: "CBL Espoir", subtitle: "Open qualifier",
    timeCap: "8 min",
    exercises: [
      "1 Muscle-up + 10 Dips + 5 Pull-up",
      "15 Back Squat @40 kg",
      "10 Pull-up @5 kg",
      "30 Dips",
      "15 Back Squat @40 kg",
      "20 Dips @10 kg",
      "1 Muscle-up ou 4 Chest Pull-up",
      "10 Dips @20 kg",
    ],
  },
  {
    id: "espoir-m-2", division: "Espoir", gender: "Men",
    round: "Routine 2", title: "CBL Espoir", subtitle: "Endurance technique",
    timeCap: "9 min",
    exercises: [
      "2 Muscle-up",
      "12 Back Squat @40 kg",
      "12 Pull-up @5 kg",
      "25 Dips",
      "12 Back Squat @35 kg",
      "18 Dips @10 kg",
      "5 Muscle-up ou 10 Chest Pull-up",
      "10 Pull-up",
    ],
  },
  {
    id: "espoir-m-3", division: "Espoir", gender: "Men",
    round: "Routine 3", title: "CBL Espoir", subtitle: "Force progressive",
    timeCap: "8 min",
    exercises: [
      "3 Chest Pull-up",
      "12 Back Squat @40 kg",
      "30 Push-up",
      "10 Pull-up @5 kg",
      "20 Dips @5 kg",
      "1 Muscle-up ou 4 Chest Pull-up",
      "15 Pull-up",
      "20 Dips",
    ],
  },
  {
    id: "espoir-m-4", division: "Espoir", gender: "Men",
    round: "Routine 4", title: "CBL Espoir", subtitle: "Volume & résistance",
    timeCap: "9 min",
    exercises: [
      "1 Muscle-up + 5 Chest Pull-up",
      "15 Back Squat @35 kg",
      "15 Pull-up @5 kg",
      "20 Dips @10 kg",
      "15 Goblet Squat @24 kg",
      "30 Push-up",
      "10 Dips @20 kg",
    ],
  },
  {
    id: "espoir-m-5", division: "Espoir", gender: "Men",
    round: "Routine 5", title: "CBL Espoir", subtitle: "Circuit complet",
    timeCap: "8 min",
    exercises: [
      "3 Muscle-up",
      "15 Back Squat @40 kg",
      "12 Pull-up @5 kg",
      "25 Dips @5 kg",
      "15 Back Squat @35 kg",
      "10 Chest Pull-up",
      "20 Dips",
    ],
  },
  {
    id: "espoir-m-s", division: "Espoir", gender: "Men",
    round: "Statiques", title: "Isométrique Espoir", subtitle: "Force de maintien",
    timeCap: "10 min",
    exercises: [
      "3× 12s Deadhang @5 kg",
      "3× 20s Bottom squat @30 kg",
      "3× 10s L-sit barres basses",
      "3× 12s Support hold @10 kg",
      "2× 10s Tuck front lever",
      "2× 10s Top pull-up hold @5 kg",
    ],
  },

  {
    id: "espoir-w-1", division: "Espoir", gender: "Women",
    round: "Routine 1", title: "CBL Espoir", subtitle: "Open qualifier",
    timeCap: "8 min",
    exercises: [
      "1 Muscle-up ou 4 Chest Pull-up",
      "12 Back Squat @30 kg",
      "8 Pull-up @5 kg",
      "24 Dips",
      "12 Goblet Squat @20 kg",
      "16 Dips @10 kg",
      "12 Pull-up",
      "8 Dips @15 kg",
    ],
  },
  {
    id: "espoir-w-2", division: "Espoir", gender: "Women",
    round: "Routine 2", title: "CBL Espoir", subtitle: "Endurance technique",
    timeCap: "9 min",
    exercises: [
      "3 Chest Pull-up",
      "10 Back Squat @30 kg",
      "10 Pull-up @5 kg",
      "20 Dips",
      "10 Back Squat @25 kg",
      "14 Dips @10 kg",
      "4 Chest Pull-up",
      "8 Pull-up",
    ],
  },
  {
    id: "espoir-w-3", division: "Espoir", gender: "Women",
    round: "Routine 3", title: "CBL Espoir", subtitle: "Force progressive",
    timeCap: "8 min",
    exercises: [
      "2 Chest Pull-up",
      "10 Back Squat @28 kg",
      "24 Push-up",
      "8 Pull-up @5 kg",
      "16 Dips @5 kg",
      "1 Muscle-up ou 3 Chest Pull-up",
      "14 Dips",
    ],
  },
  {
    id: "espoir-w-4", division: "Espoir", gender: "Women",
    round: "Routine 4", title: "CBL Espoir", subtitle: "Volume & résistance",
    timeCap: "9 min",
    exercises: [
      "1 Muscle-up ou 3 Chest Pull-up",
      "12 Back Squat @30 kg",
      "12 Pull-up @5 kg",
      "16 Dips @10 kg",
      "12 Goblet Squat @20 kg",
      "24 Push-up",
      "8 Dips @15 kg",
    ],
  },
  {
    id: "espoir-w-5", division: "Espoir", gender: "Women",
    round: "Routine 5", title: "CBL Espoir", subtitle: "Circuit complet",
    timeCap: "8 min",
    exercises: [
      "2 Muscle-up ou 6 Chest Pull-up",
      "12 Back Squat @30 kg",
      "10 Pull-up @5 kg",
      "20 Dips @5 kg",
      "10 Back Squat @25 kg",
      "8 Chest Pull-up",
      "16 Dips",
    ],
  },
  {
    id: "espoir-w-s", division: "Espoir", gender: "Women",
    round: "Statiques", title: "Isométrique Espoir", subtitle: "Force de maintien",
    timeCap: "10 min",
    exercises: [
      "3× 10s Deadhang @5 kg",
      "3× 20s Bottom squat @25 kg",
      "3× 8s L-sit barres basses",
      "3× 10s Support hold @BW",
      "2× 8s Tuck front lever",
      "2× 8s Top pull-up hold @5 kg",
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  //  SEMI-PRO
  //  Ordre: COMPOUND lourd → LEGS → PULL → PUSH → COMPOUND → LEGS → PUSH
  // ═══════════════════════════════════════════════════════════════

  {
    id: "sp-m-1", division: "Semi-Pro", gender: "Men",
    round: "Routine 1", title: "CBL Semi-Pro", subtitle: "Challenge technique",
    timeCap: "10 min",
    exercises: [
      "3 Muscle-up @5 kg",
      "15 Back Squat @50 kg",
      "12 Pull-up @10 kg",
      "40 Dips",
      "15 Back Squat @45 kg",
      "5 Muscle-up",
      "15 Dips @30 kg",
      "8 Muscle-up ou 15 Chest Pull-up",
    ],
  },
  {
    id: "sp-m-2", division: "Semi-Pro", gender: "Men",
    round: "Routine 2", title: "CBL Semi-Pro", subtitle: "Force & volume",
    timeCap: "11 min",
    exercises: [
      "1 Muscle-up @10 kg",
      "18 Back Squat @50 kg",
      "10 Pull-up @10 kg",
      "40 Push-up",
      "5 Muscle-up",
      "20 Dips @20 kg",
      "12 Pull-up @10 kg",
      "10 Dips @40 kg",
    ],
  },
  {
    id: "sp-m-3", division: "Semi-Pro", gender: "Men",
    round: "Routine 3", title: "CBL Semi-Pro", subtitle: "Endurance avancée",
    timeCap: "10 min",
    exercises: [
      "2 Muscle-up @5 kg",
      "15 Back Squat @48 kg",
      "15 Pull-up @10 kg",
      "35 Dips",
      "8 Muscle-up",
      "40 Push-up",
      "10 Dips @35 kg",
    ],
  },
  {
    id: "sp-m-4", division: "Semi-Pro", gender: "Men",
    round: "Routine 4", title: "CBL Semi-Pro", subtitle: "Montée en charge",
    timeCap: "11 min",
    exercises: [
      "5 Chest Pull-up @10 kg",
      "18 Back Squat @50 kg",
      "12 Pull-up @10 kg",
      "45 Dips",
      "3 Muscle-up @5 kg",
      "15 Pull-up",
      "12 Dips @40 kg",
      "6 Muscle-up",
    ],
  },
  {
    id: "sp-m-5", division: "Semi-Pro", gender: "Men",
    round: "Routine 5", title: "CBL Semi-Pro", subtitle: "Circuit pro",
    timeCap: "10 min",
    exercises: [
      "1 Muscle-up @10 kg",
      "18 Back Squat @50 kg",
      "15 Pull-up @10 kg",
      "40 Dips",
      "3 Muscle-up @5 kg",
      "40 Push-up",
      "5 Muscle-up",
      "10 Dips @40 kg",
    ],
  },
  {
    id: "sp-m-s", division: "Semi-Pro", gender: "Men",
    round: "Statiques", title: "Isométrique Semi-Pro", subtitle: "Maîtrise du corps",
    timeCap: "10 min",
    exercises: [
      "3× 10s Tuck front lever",
      "3× 15s Bottom squat @40 kg",
      "3× 10s L-sit barres",
      "3× 12s Support hold @20 kg",
      "2× 8s Straddle front lever",
      "2× 8s Planche lean (bras tendus)",
    ],
  },

  {
    id: "sp-w-1", division: "Semi-Pro", gender: "Women",
    round: "Routine 1", title: "CBL Semi-Pro", subtitle: "Challenge technique",
    timeCap: "10 min",
    exercises: [
      "2 Muscle-up @5 kg",
      "12 Back Squat @38 kg",
      "10 Pull-up @5 kg",
      "30 Dips",
      "12 Back Squat @35 kg",
      "4 Muscle-up",
      "12 Dips @20 kg",
      "6 Muscle-up ou 10 Chest Pull-up",
    ],
  },
  {
    id: "sp-w-2", division: "Semi-Pro", gender: "Women",
    round: "Routine 2", title: "CBL Semi-Pro", subtitle: "Force & volume",
    timeCap: "11 min",
    exercises: [
      "1 Muscle-up @5 kg",
      "14 Back Squat @36 kg",
      "8 Pull-up @5 kg",
      "30 Push-up",
      "4 Muscle-up",
      "16 Dips @15 kg",
      "10 Pull-up @5 kg",
      "8 Dips @25 kg",
    ],
  },
  {
    id: "sp-w-3", division: "Semi-Pro", gender: "Women",
    round: "Routine 3", title: "CBL Semi-Pro", subtitle: "Endurance avancée",
    timeCap: "10 min",
    exercises: [
      "1 Muscle-up @5 kg",
      "12 Back Squat @36 kg",
      "10 Pull-up @5 kg",
      "28 Dips",
      "5 Muscle-up",
      "30 Push-up",
      "8 Dips @25 kg",
    ],
  },
  {
    id: "sp-w-4", division: "Semi-Pro", gender: "Women",
    round: "Routine 4", title: "CBL Semi-Pro", subtitle: "Montée en charge",
    timeCap: "11 min",
    exercises: [
      "4 Chest Pull-up @5 kg",
      "14 Back Squat @38 kg",
      "10 Pull-up @5 kg",
      "32 Dips",
      "2 Muscle-up @5 kg",
      "12 Pull-up",
      "8 Dips @25 kg",
      "4 Muscle-up",
    ],
  },
  {
    id: "sp-w-5", division: "Semi-Pro", gender: "Women",
    round: "Routine 5", title: "CBL Semi-Pro", subtitle: "Circuit pro",
    timeCap: "10 min",
    exercises: [
      "1 Muscle-up @5 kg",
      "14 Back Squat @38 kg",
      "10 Pull-up @5 kg",
      "30 Dips",
      "2 Muscle-up",
      "30 Push-up",
      "4 Muscle-up",
      "8 Dips @25 kg",
    ],
  },
  {
    id: "sp-w-s", division: "Semi-Pro", gender: "Women",
    round: "Statiques", title: "Isométrique Semi-Pro", subtitle: "Maîtrise du corps",
    timeCap: "10 min",
    exercises: [
      "3× 8s Tuck front lever",
      "3× 15s Bottom squat @32 kg",
      "3× 8s L-sit barres",
      "3× 10s Support hold @15 kg",
      "2× 6s Straddle front lever",
      "2× 6s Planche lean (bras tendus)",
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  //  ELITE
  //  Ordre: COMPOUND lourd → LEGS → PULL pesé → PUSH → COMPOUND → LEGS → PUSH lourd
  //  Aucun muscle-up consécutif — toujours séparé par jambes ou tirage
  // ═══════════════════════════════════════════════════════════════

  {
    id: "elite-m-1", division: "Elite", gender: "Men",
    round: "Routine 1", title: "CBL Elite", subtitle: "Battle endurance",
    timeCap: "12 min",
    exercises: [
      "1 Muscle-up @15 kg",
      "20 Back Squat @60 kg",
      "3 Muscle-up @10 kg",
      "20 Pull-up @15 kg",
      "50 Dips",
      "5 Muscle-up @10 kg",
      "50 Push-up",
      "7 Muscle-up",
      "10 Dips @50 kg",
    ],
  },
  {
    id: "elite-m-2", division: "Elite", gender: "Men",
    round: "Routine 2", title: "CBL Elite", subtitle: "Force maximale",
    timeCap: "12 min",
    exercises: [
      "1 Muscle-up @20 kg",
      "18 Back Squat @65 kg",
      "3 Muscle-up @15 kg",
      "20 Pull-up @15 kg",
      "5 Muscle-up @10 kg",
      "50 Push-up",
      "8 Muscle-up",
      "10 Dips @50 kg",
    ],
  },
  {
    id: "elite-m-3", division: "Elite", gender: "Men",
    round: "Routine 3", title: "CBL Elite", subtitle: "Endurance explosive",
    timeCap: "11 min",
    exercises: [
      "3 Muscle-up @15 kg",
      "20 Back Squat @60 kg",
      "15 Pull-up @15 kg",
      "50 Dips",
      "5 Muscle-up @10 kg",
      "50 Push-up",
      "12 Chest Pull-up",
      "7 Muscle-up",
      "10 Dips @50 kg",
    ],
  },
  {
    id: "elite-m-4", division: "Elite", gender: "Men",
    round: "Routine 4", title: "CBL Elite", subtitle: "Circuit lourd",
    timeCap: "12 min",
    exercises: [
      "1 Muscle-up @15 kg",
      "20 Back Squat @60 kg",
      "5 Muscle-up @10 kg",
      "15 Pull-up @20 kg",
      "50 Dips",
      "50 Push-up",
      "5 Muscle-up",
      "10 Dips @55 kg",
    ],
  },
  {
    id: "elite-m-5", division: "Elite", gender: "Men",
    round: "Routine 5", title: "CBL Elite", subtitle: "Finale compétition",
    timeCap: "12 min",
    exercises: [
      "1 Muscle-up @20 kg",
      "18 Back Squat @65 kg",
      "3 Muscle-up @15 kg",
      "20 Pull-up @15 kg",
      "50 Dips",
      "5 Muscle-up @10 kg",
      "50 Push-up",
      "8 Muscle-up",
      "10 Dips @55 kg",
      "12 Chest Pull-up",
    ],
  },
  {
    id: "elite-m-s", division: "Elite", gender: "Men",
    round: "Statiques", title: "Isométrique Elite", subtitle: "Contrôle absolu",
    timeCap: "12 min",
    exercises: [
      "3× 8s Front lever",
      "3× 15s Bottom squat @50 kg",
      "3× 10s L-sit full barres",
      "2× 8s Back lever",
      "3× 10s Support hold @30 kg",
      "2× 6s Planche lean avancé",
      "2× 5s Handstand (mur, contrôlé)",
    ],
  },

  {
    id: "elite-w-1", division: "Elite", gender: "Women",
    round: "Routine 1", title: "CBL Elite", subtitle: "Battle endurance",
    timeCap: "12 min",
    exercises: [
      "1 Muscle-up @5 kg",
      "18 Back Squat @40 kg",
      "3 Muscle-up",
      "12 Pull-up @5 kg",
      "40 Dips",
      "4 Muscle-up",
      "40 Push-up",
      "12 Chest Pull-up",
      "8 Dips @20 kg",
    ],
  },
  {
    id: "elite-w-2", division: "Elite", gender: "Women",
    round: "Routine 2", title: "CBL Elite", subtitle: "Force maximale",
    timeCap: "12 min",
    exercises: [
      "1 Muscle-up @8 kg",
      "16 Back Squat @42 kg",
      "3 Muscle-up @5 kg",
      "15 Pull-up @5 kg",
      "4 Muscle-up",
      "40 Push-up",
      "5 Muscle-up",
      "8 Dips @22 kg",
    ],
  },
  {
    id: "elite-w-3", division: "Elite", gender: "Women",
    round: "Routine 3", title: "CBL Elite", subtitle: "Endurance explosive",
    timeCap: "11 min",
    exercises: [
      "2 Muscle-up @5 kg",
      "18 Back Squat @40 kg",
      "12 Pull-up @5 kg",
      "40 Dips",
      "4 Muscle-up",
      "40 Push-up",
      "5 Muscle-up",
      "10 Chest Pull-up",
      "8 Dips @20 kg",
    ],
  },
  {
    id: "elite-w-4", division: "Elite", gender: "Women",
    round: "Routine 4", title: "CBL Elite", subtitle: "Circuit lourd",
    timeCap: "12 min",
    exercises: [
      "1 Muscle-up @8 kg",
      "16 Back Squat @42 kg",
      "4 Muscle-up @5 kg",
      "12 Pull-up @8 kg",
      "40 Dips",
      "40 Push-up",
      "5 Muscle-up",
      "8 Dips @25 kg",
    ],
  },
  {
    id: "elite-w-5", division: "Elite", gender: "Women",
    round: "Routine 5", title: "CBL Elite", subtitle: "Finale compétition",
    timeCap: "12 min",
    exercises: [
      "1 Muscle-up @8 kg",
      "16 Back Squat @42 kg",
      "3 Muscle-up @5 kg",
      "15 Pull-up @5 kg",
      "40 Dips",
      "4 Muscle-up",
      "40 Push-up",
      "5 Muscle-up",
      "8 Dips @25 kg",
      "10 Chest Pull-up",
    ],
  },
  {
    id: "elite-w-s", division: "Elite", gender: "Women",
    round: "Statiques", title: "Isométrique Elite", subtitle: "Contrôle absolu",
    timeCap: "12 min",
    exercises: [
      "3× 6s Front lever",
      "3× 15s Bottom squat @35 kg",
      "3× 8s L-sit full barres",
      "2× 6s Back lever",
      "3× 8s Support hold @20 kg",
      "2× 5s Planche lean avancé",
      "2× 5s Handstand (mur, contrôlé)",
    ],
  },
];
